name: Build & Push Image to Docker Hub

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN_OR_PASSWORD }}
            - name: Build the Docker image
              run: docker build --file Dockerfile --tag anushibin007/jira-automater:latest .
            - name: Push the Image to Docker Hub
              run: docker push anushibin007/jira-automater:latest
